### PR TITLE
Some suggestions for the FASTA Raw/Value types

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes please, take a look. I think this simplifies things a bit without waiting for a miracle to happen in cosas.
I suggest the same for FastQ.

**Comment by eparejatobes** [comment]
fine, LGTM

**Comment by laughedelic** [comment]
Well.. I had some more changes that I couldn't push yesterday without internet. But nothing really important and mostly about fastq that you solved in d213c04.

**Comment by eparejatobes** [comment]
@laughedelic if there's something else just tell me :ok_hand: :+1:

**Pull request merged**
